/*
  # AI Course Director - Database Schema

  1. New Tables
    - `ai_generation_cache`
      - Stores cached AI responses keyed by prompt hash
      - Prevents redundant API calls for identical requests
      - Includes TTL for cache expiry
    - `ai_audit_reports`
      - Stores course audit/health reports generated by the AI
      - Links to courses with scores and recommendations
    - `ai_generation_jobs`
      - Tracks long-running AI generation tasks (course creation, bulk SEO)
      - Stores progress, status, and results

  2. Security
    - RLS enabled on all tables
    - Only admin/content_editor/instructor roles can access
    - All AI actions logged via existing admin_audit_log

  3. Indexes
    - prompt_hash for fast cache lookups
    - course_id for audit report retrieval
    - status + created_at for job queue management
*/

-- AI Response Cache
CREATE TABLE IF NOT EXISTS ai_generation_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  prompt_hash text NOT NULL,
  prompt_summary text NOT NULL,
  model text NOT NULL DEFAULT 'gpt-4o',
  response jsonb NOT NULL DEFAULT '{}'::jsonb,
  tokens_used integer NOT NULL DEFAULT 0,
  cost_usd numeric(10,6) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days')
);

ALTER TABLE ai_generation_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff can manage AI cache"
  ON ai_generation_cache FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  );

CREATE INDEX IF NOT EXISTS idx_ai_cache_prompt_hash ON ai_generation_cache(prompt_hash);
CREATE INDEX IF NOT EXISTS idx_ai_cache_expires ON ai_generation_cache(expires_at);

-- AI Audit Reports
CREATE TABLE IF NOT EXISTS ai_audit_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  generated_by uuid NOT NULL REFERENCES auth.users(id),
  overall_score integer NOT NULL DEFAULT 0,
  completeness_score integer NOT NULL DEFAULT 0,
  regulatory_score integer NOT NULL DEFAULT 0,
  engagement_score integer NOT NULL DEFAULT 0,
  seo_score integer NOT NULL DEFAULT 0,
  findings jsonb NOT NULL DEFAULT '[]'::jsonb,
  recommendations jsonb NOT NULL DEFAULT '[]'::jsonb,
  media_suggestions jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ai_audit_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff can view audit reports"
  ON ai_audit_reports FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  );

CREATE POLICY "Staff can create audit reports"
  ON ai_audit_reports FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  );

CREATE INDEX IF NOT EXISTS idx_ai_audit_course ON ai_audit_reports(course_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_created ON ai_audit_reports(created_at DESC);

-- AI Generation Jobs
CREATE TABLE IF NOT EXISTS ai_generation_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  job_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  course_id uuid REFERENCES courses(id) ON DELETE SET NULL,
  input_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  progress integer NOT NULL DEFAULT 0,
  result jsonb,
  error_message text,
  tokens_used integer NOT NULL DEFAULT 0,
  cost_usd numeric(10,6) NOT NULL DEFAULT 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT valid_status CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')),
  CONSTRAINT valid_progress CHECK (progress >= 0 AND progress <= 100),
  CONSTRAINT valid_job_type CHECK (job_type IN (
    'course_generate', 'lesson_generate', 'quiz_generate',
    'case_study_generate', 'seo_optimise', 'course_audit',
    'bulk_seo', 'content_enhance'
  ))
);

ALTER TABLE ai_generation_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff can view own generation jobs"
  ON ai_generation_jobs FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  );

CREATE POLICY "Staff can create generation jobs"
  ON ai_generation_jobs FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  );

CREATE POLICY "Staff can update own generation jobs"
  ON ai_generation_jobs FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role IN ('super_admin', 'admin', 'content_editor', 'instructor')
    )
  );

CREATE INDEX IF NOT EXISTS idx_ai_jobs_user ON ai_generation_jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_jobs_status ON ai_generation_jobs(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_jobs_course ON ai_generation_jobs(course_id);
